@startuml
title dispatchOrder Fishing Spot Flow

actor "User" as User
participant "P2P\nSwap" as P2PSwap #BEA1EC
participant "EVVM" as Evvm #72F6AA

activate User
User -> User: Sign dispatch\norder using ERC-191
User -> User: Sign payment\nusing ERC-191

User -> P2PSwap: Send payload

deactivate User


activate P2PSwap #BEA1EC
P2PSwap -> P2PSwap: Verify input data
alt "Input data is valid"
        
    P2PSwap -> Evvm: Execute payment

    activate Evvm #72F6AA

    alt "Payment is valid"
        Evvm -> P2PSwap: Reward with MATE\nand give priority fee

        P2PSwap -> Evvm: Execute dispatch order\nfor Seller and Buyer (User)
        Evvm -> P2PSwap: Reward with MATE\nfor both transactions
            
        P2PSwap -> P2PSwap: Make order\nas completed

        alt "User has sMate"
        P2PSwap -> User: Reward with MATE\nand token\n(if user gives a priority fee)
        end 

        P2PSwap -> P2PSwap: Update P2P nonce for\nuser
            
    else "Payment is invalid"
        Evvm -> P2PSwap : revert
        deactivate Evvm
        P2PSwap -> User: revert
    end
            
else "Input data is invalid"
    P2PSwap -> User: revert
    deactivate P2PSwap
end


@enduml