@startuml
title cancelOrder Permissionless Flow

actor "User" as User
participant "P2P\nSwap" as P2PSwap #BEA1EC
participant "EVVM" as Evvm #72F6AA

User -> User: Sign cancel order\nusing ERC-191

alt #LightGray "User wants to \ngive a priority fee"
    User -> User: Sign payment\nusing ERC-191
end


    User -> P2PSwap: Send payload
    activate P2PSwap #BEA1EC
    P2PSwap -> P2PSwap: Verify input data
    alt "Input data is valid"
        alt #LightGray "The transaction has priority fee" 
            P2PSwap -> Evvm: Execute payment
            alt "Payment is valid"
                Evvm -> P2PSwap: Reward ang give\npriority fee
            else "Payment is invalid"
                Evvm -> P2PSwap : revert
                deactivate Evvm
                P2PSwap -> User: revert
            end
        end

        P2PSwap -> P2PSwap: Cancel order

        alt "Fisher has sMate"
            P2PSwap -> User: Reward with Mate\nand token\n(if user gives a priority fee)
        end

        P2PSwap -> P2PSwap: Update P2P nonce for\nuser
            
    else "Input data is invalid"
        P2PSwap -> User: revert
    end
@enduml