import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    "QuickStart",
    "ProcessOfATransaction",
    {
      type: "category",
      label: "Contracts",
      items: [{ type: "autogenerated", dirName: "04-Contracts" }],
    },
    {
      type: "category",
      label: "Signature Structures",
      items: [{ type: "autogenerated", dirName: "05-SignatureStructures" }],
    },
    "HowToMakeAEVVMService",
    
    {
      type: "category",
      label: "Libraries",
      items: [{ type: "autogenerated", dirName: "07-Libraries" }],
    },
    {
      type: "category",
      label: "Registry EVVM",
      link: {
        type: "doc",
        id: "RegistryEvvm/Overview",
      },
      items: [{ type: "autogenerated", dirName: "08-RegistryEvvm" }],
    },
    {
      type: "category",
      label: "EVVM CLI",
      items: [{ type: "autogenerated", dirName: "09-evvmCli" }],
    },
    {
      type: "link",
      label : "Scaffold EVVM",
      href : "https://github.com/EVVM-org/scaffold-evvm",
    },
    {
      type: "link",
      label: "EVVM Full Documentation for LLM",
      href: "https://evvm.info/llms-full.txt",
    },
    "EVVMNoncommercialLicense",
  ],
};

export default sidebars;
