@startuml

<style>
document {
  BackGroundColor white
}
</style>

title External Station: depositCoin() Flow (Failed Paths)

actor "User" as user
participant "ExternalStation" as ext #66CCFF

activate user
user -> ext : depositCoin(...){value}
deactivate user

activate ext
alt #f5b7b1 amount == 0
    ext -x user : Revert with DepositAmountMustBeGreaterThanZero()
else #f5b7b1 insufficient value
    ext -x user : Revert with InvalidDepositAmount()
else #f5b7b1 protocol error
    ext -x user : Revert (invalid protocol)
end

deactivate ext

@enduml