@startuml


<style>
document {
  BackGroundColor white
}

</style>

actor "Fisher or User" as executor
participant "EVVM" as evvm #00EE20



title Async Nonce Transaction\nGeneric Flow Example


executor -> evvm : Execute transaction

evvm -> evvm : Read nonce state using\nasyncUsedNonce[userAddress][nonce]

alt #f5b7b1 asyncUsedNonce [userAddress][nonce] == true

  evvm -> executor : Revert transaction

else #white else

  hnote over evvm : payment process

  evvm -> evvm : asyncUsedNonce[userAddress][nonce] = true

end



@enduml